# Replace handles/links with your actual accounts once available
github: ["flyingriverhorse"]
open_collective: ""
patreon: ""
ko_fi: ""
custom:
  - "https://buymeacoffee.com/YOUR_HANDLE"
  - "https://opencollective.com/YOUR_COLLECTIVE"