---
engines:
  flake8:
    enabled: true
  pylint:
    enabled: true
    python_version: 3
  bandit:
    enabled: true
  trivy:
    enabled: false

exclude_paths:
  - "tests/**"
  - "testingdb/**"
  - "temp/**"
  - "migrations/**"
  - "uv.lock"
  - "site/**"
  - "static/**"
  - "**/*.min.css"
  - "**/*.min.js"
