import { registry } from './NodeRegistry';
import { DataPreviewNode } from '../../modules/nodes/inspection/DataPreviewNode';
import { DatasetNode } from '../../modules/nodes/data/DatasetNode';
import { DropColumnsNode } from '../../modules/nodes/processing/DropColumnsNode';
import { ImputationNode } from '../../modules/nodes/processing/ImputationNode';
import { ScalingNode } from '../../modules/nodes/processing/ScalingNode';
import { ClassificationNode } from '../../modules/nodes/modeling/ClassificationNode';
import { RegressionNode } from '../../modules/nodes/modeling/RegressionNode';
import { TextClassificationNode } from '../../modules/nodes/modeling/TextClassificationNode';
import { EnsembleNode } from '../../modules/nodes/modeling/EnsembleNode';
import { SegmentationNode } from '../../modules/nodes/modeling/SegmentationNode';
import { FeatureSelectionNode } from '../../modules/nodes/processing/FeatureSelectionNode';
import { TrainTestSplitNode } from '../../modules/nodes/modeling/TrainTestSplitNode';
import { FeatureTargetSplitNode } from '../../modules/nodes/modeling/FeatureTargetSplitNode';
import { DropRowsNode } from '../../modules/nodes/processing/DropRowsNode';
import { DeduplicationNode } from '../../modules/nodes/processing/DeduplicationNode';
import { CastTypeNode } from '../../modules/nodes/processing/CastTypeNode';
import { MissingIndicatorNode } from '../../modules/nodes/processing/MissingIndicatorNode';
import { EncodingNode } from '../../modules/nodes/processing/EncodingNode';
import { TimeSeriesNode } from '../../modules/nodes/processing/TimeSeriesNode';
import { OutlierNode } from '../../modules/nodes/processing/OutlierNode';
import { TransformationNode } from '../../modules/nodes/processing/TransformationNode';
import { BinningNode } from '../../modules/nodes/processing/BinningNode';
import { ResamplingNode } from '../../modules/nodes/processing/ResamplingNode';
import { FeatureGenerationNode } from '../../modules/nodes/processing/FeatureGenerationNode';
import { PolynomialFeaturesNode } from '../../modules/nodes/processing/PolynomialFeaturesNode';
import { FeatureInteractionNode } from '../../modules/nodes/processing/FeatureInteractionNode';
import { TextCleaningNode } from '../../modules/nodes/processing/TextCleaningNode';
import {
  CountVectorizerNode,
  TfidfVectorizerNode,
  HashingVectorizerNode,
} from '../../modules/nodes/processing/VectorizerNodes';
import { TokenizerNode, SentenceEmbedderNode } from '../../modules/nodes/processing/TextNodes';
import { ValueReplacementNode } from '../../modules/nodes/processing/ValueReplacementNode';
import { AliasReplacementNode } from '../../modules/nodes/processing/AliasReplacementNode';
import { InvalidValueReplacementNode } from '../../modules/nodes/processing/InvalidValueReplacementNode';

export const initializeRegistry = () => {
  registry.register(DataPreviewNode);
  registry.register(DatasetNode);
  registry.register(DropColumnsNode);
  registry.register(ImputationNode);
  registry.register(ScalingNode);
  registry.register(OutlierNode);
  registry.register(TransformationNode);
  registry.register(BinningNode);
  registry.register(ResamplingNode);
  registry.register(FeatureGenerationNode);
  registry.register(PolynomialFeaturesNode);
  registry.register(FeatureInteractionNode);
  registry.register(TextCleaningNode);
  registry.register(CountVectorizerNode);
  registry.register(TfidfVectorizerNode);
  registry.register(HashingVectorizerNode);
  registry.register(TokenizerNode);
  registry.register(SentenceEmbedderNode);
  registry.register(ValueReplacementNode);
  registry.register(AliasReplacementNode);
  registry.register(InvalidValueReplacementNode);
  registry.register(EncodingNode);
  registry.register(TimeSeriesNode);
  registry.register(FeatureSelectionNode);
  registry.register(TrainTestSplitNode);
  registry.register(FeatureTargetSplitNode);
  registry.register(DropRowsNode);
  registry.register(DeduplicationNode);
  registry.register(CastTypeNode);
  registry.register(MissingIndicatorNode);
  registry.register(ClassificationNode);
  registry.register(RegressionNode);
  registry.register(TextClassificationNode);
  registry.register(EnsembleNode);
  registry.register(SegmentationNode);
};
