# Databricks notebook source
# Generated by refresh_feature_graph.py; edit config/features.yml.
"""Build or merge a configured Spark feature domain with visible diagnostics."""

from skyulf.integrations.databricks.jobs.features.feature_task import run_feature_notebook
from skyulf.integrations.databricks.jobs.shared.notebook_diagnostics import notebook_task

if __name__ == "__main__":
    with notebook_task("feature_tables", globals()["dbutils"]):
        run_feature_notebook(globals()["spark"], globals()["dbutils"])
