"""Configure the shared monitoring dashboard, then validate and redeploy the Bundle.

Use --dashboard-url with the published monitoring dashboard URL, or --dashboard-id.
An optional --warehouse-id overrides the published dashboard's warehouse.
Use --create-dashboard --warehouse-id only in the one project owning the dashboard.
Use --disable to remove refresh while preserving dashboard ownership.
No API calls or emails are made.
"""

import argparse
import json
import re
from pathlib import Path
from textwrap import indent
from urllib.parse import urlsplit

HEADER = "# Generated by src/tools/configure_monitoring_dashboard.py.\n"
ID_PATTERN = r"(?:[0-9a-fA-F]{32}|[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12})"
OWNER_TARGET = "# Dashboard owner target: "
OWNED_ID = "${resources.dashboards.monitoring_dashboard.id}"


def _dashboard_id(dashboard_id, dashboard_url):
    """Accept a dashboard identifier or extract it from its published HTTPS URL."""
    if dashboard_id and dashboard_url:
        raise ValueError("Provide dashboard_id or dashboard_url, not both.")
    if dashboard_url:
        parsed = urlsplit(dashboard_url)
        match = re.fullmatch(
            r"/(?:sql/)?dashboardsv3/([^/]+)(?:/published(?:/pages/[^/]+)?)?/?", parsed.path
        )
        if parsed.scheme != "https" or not parsed.netloc or not match:
            raise ValueError("Use the published dashboard HTTPS URL containing /dashboardsv3/ID.")
        dashboard_id = match.group(1)
    if dashboard_id and not re.fullmatch(ID_PATTERN, dashboard_id):
        raise ValueError("Use the dashboard's 32-digit hexadecimal ID or UUID.")
    return dashboard_id


def _validate_options(dashboard_id, warehouse_id, targets, create_dashboard):
    """Reject incomplete or ambiguous ownership before changing local configuration."""
    if warehouse_id and (
        not (dashboard_id or create_dashboard) or not re.fullmatch(r"[0-9a-fA-F]{16}", warehouse_id)
    ):
        raise ValueError("warehouse_id requires a dashboard and a 16-digit hexadecimal ID.")
    if create_dashboard:
        if dashboard_id or not warehouse_id:
            raise ValueError(
                "Dashboard ownership requires warehouse_id and no dashboard ID or URL."
            )
        if len(set(targets)) != 1:
            raise ValueError(
                "Choose one owner target; other projects must reuse the dashboard URL."
            )


def _read_owned(path):
    """Read only overlays generated by this helper before any write or removal."""
    content = path.read_text(encoding="utf-8") if path.exists() else ""
    if path.exists() and not content.startswith(HEADER):
        raise ValueError(f"Refusing to change {path}: not generated by this helper.")
    return content


def _owner_overlay(project, warehouse_id, target, existing):
    """Render a single target's managed dashboard without moving existing ownership."""
    header = HEADER + OWNER_TARGET + json.dumps(target) + "\n"
    if existing and not existing.startswith(header):
        raise ValueError(
            "Keep the existing dashboard owner target; ownership cannot be moved here."
        )
    asset = project / "src/monitoring/monitoring.lvdash.json"
    if not asset.is_file():
        raise ValueError(f"Missing dashboard asset: {asset}")
    resource = f"""variables:
  monitoring_dashboard_url: "${{workspace.host}}/dashboardsv3/{OWNED_ID}/published"
resources:
  dashboards:
    monitoring_dashboard:
      display_name: "${{bundle.name}} monitoring"
      file_path: ../src/monitoring/monitoring.lvdash.json
      warehouse_id: {json.dumps(warehouse_id)}
      dataset_catalog: ${{var.monitoring_catalog}}
      dataset_schema: ${{var.monitoring_schema}}
      embed_credentials: false
"""
    return header + "targets:\n" + f"  {json.dumps(target)}:\n" + indent(resource, "    ")


def _refresh_overlay(dashboard_id, warehouse_id, targets):
    """Render target-specific native refresh tasks without changing the base job graph."""
    warehouse = f"\n              warehouse_id: {json.dumps(warehouse_id)}" if warehouse_id else ""
    resource = f"""resources:
  jobs:
    monitoring:
      tasks:
        - task_key: dashboard_refresh_enabled
          description: Refresh only when monitoring is enabled outside development mode
          depends_on:
            - task_key: evaluate_retraining
          condition_task:
            op: EQUAL_TO
            left: "${{bundle.mode}}:${{var.monitoring_enabled}}"
            right: "production:true"
        - task_key: refresh_monitoring_dashboard
          description: Refresh the published shared dashboard after monitoring evidence is saved
          depends_on:
            - task_key: dashboard_refresh_enabled
              outcome: "true"
          timeout_seconds: ${{var.monitoring_task_timeout_seconds}}
          max_retries: ${{var.monitoring_max_retries}}
          min_retry_interval_millis: 60000
          dashboard_task:
              dashboard_id: {json.dumps(dashboard_id)}{warehouse}
"""
    return (
        HEADER
        + "targets:\n"
        + "".join(
            f"  {json.dumps(target)}:\n" + indent(resource, "    ")
            for target in dict.fromkeys(targets)
        )
    )


def configure(
    project,
    *,
    dashboard_id="",
    dashboard_url="",
    warehouse_id="",
    targets=("test",),
    create_dashboard=False,
):
    """Configure refresh or explicit ownership; disabling always preserves the dashboard."""
    dashboard_id = _dashboard_id(dashboard_id, dashboard_url)
    if not targets or any(not re.fullmatch(r"[A-Za-z0-9_-]+", target) for target in targets):
        raise ValueError("Specify target names using letters, numbers, underscores or hyphens.")
    _validate_options(dashboard_id, warehouse_id, targets, create_dashboard)
    path = project / "resources/monitoring_dashboard.job.yml"
    owner_path = project / "resources/monitoring.dashboard.yml"
    _read_owned(path)
    existing_owner = _read_owned(owner_path)
    if create_dashboard:
        owner = _owner_overlay(project, warehouse_id, targets[0], existing_owner)
        dashboard_id = OWNED_ID
    elif existing_owner and dashboard_id:
        raise ValueError("Keep dashboard ownership: use --create-dashboard, or --disable refresh.")
    if not dashboard_id:
        path.unlink(missing_ok=True)
        return path
    refresh = _refresh_overlay(dashboard_id, warehouse_id, targets)
    if create_dashboard:
        owner_path.write_text(owner, encoding="utf-8")
    path.write_text(refresh, encoding="utf-8")
    return path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--dashboard-url", default="")
    source.add_argument("--dashboard-id", default="")
    source.add_argument("--create-dashboard", action="store_true")
    source.add_argument("--disable", action="store_true")
    parser.add_argument("--warehouse-id", default="")
    parser.add_argument(
        "--target",
        action="append",
        help="Bundle target; repeat for multiple targets (default: test)",
    )
    args = parser.parse_args()
    overlay = configure(
        Path(__file__).resolve().parents[2],
        dashboard_id=args.dashboard_id,
        dashboard_url=args.dashboard_url,
        warehouse_id=args.warehouse_id,
        targets=tuple(args.target or ["test"]),
        create_dashboard=args.create_dashboard,
    )
    print("Dashboard refresh", "disabled" if args.disable else "configured", "in", overlay)
    print("Validate and redeploy the Bundle before running monitoring.")
