"""Configure optional native dashboard refresh, then validate and redeploy the Bundle.

Use --dashboard-url with the published monitoring dashboard URL, or --dashboard-id.
An optional --warehouse-id overrides the published dashboard's warehouse.
Use --disable to remove the generated overlay. No API calls or emails are made.
"""

import argparse
import json
import re
from pathlib import Path
from textwrap import indent
from urllib.parse import urlsplit

HEADER = "# Generated by src/tools/configure_monitoring_dashboard.py.\n"
ID_PATTERN = r"(?:[0-9a-fA-F]{32}|[0-9a-fA-F]{8}(?:-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12})"


def _dashboard_id(dashboard_id, dashboard_url):
    """Accept a dashboard identifier or extract it from its published HTTPS URL."""
    if dashboard_id and dashboard_url:
        raise ValueError("Provide dashboard_id or dashboard_url, not both.")
    if dashboard_url:
        parsed = urlsplit(dashboard_url)
        match = re.fullmatch(
            r"/(?:sql/)?dashboardsv3/([^/]+)(?:/published(?:/pages/[^/]+)?)?/?", parsed.path
        )
        if parsed.scheme != "https" or not parsed.netloc or not match:
            raise ValueError("Use the published dashboard HTTPS URL containing /dashboardsv3/ID.")
        dashboard_id = match.group(1)
    if dashboard_id and not re.fullmatch(ID_PATTERN, dashboard_id):
        raise ValueError("Use the dashboard's 32-digit hexadecimal ID or UUID.")
    return dashboard_id


def configure(project, *, dashboard_id="", dashboard_url="", warehouse_id="", targets=("test",)):
    """Write or remove only the owned dashboard resource overlay; preserve existing jobs."""
    dashboard_id = _dashboard_id(dashboard_id, dashboard_url)
    if warehouse_id and (not dashboard_id or not re.fullmatch(r"[0-9a-fA-F]{16}", warehouse_id)):
        raise ValueError("warehouse_id requires a dashboard and a 16-digit hexadecimal ID.")
    if not targets or any(not re.fullmatch(r"[A-Za-z0-9_-]+", target) for target in targets):
        raise ValueError("Specify target names using letters, numbers, underscores or hyphens.")
    path = project / "resources/monitoring_dashboard.job.yml"
    if path.exists() and not path.read_text(encoding="utf-8").startswith(HEADER):
        raise ValueError(f"Refusing to change {path}: not generated by this helper.")
    if not dashboard_id:
        path.unlink(missing_ok=True)
        return path
    warehouse = f"\n              warehouse_id: {json.dumps(warehouse_id)}" if warehouse_id else ""
    resource = f"""resources:
  jobs:
    monitoring:
      tasks:
        - task_key: dashboard_refresh_enabled
          description: Refresh only when monitoring is enabled outside development mode
          depends_on:
            - task_key: evaluate_retraining
          condition_task:
            op: EQUAL_TO
            left: "${{bundle.mode}}:${{var.monitoring_enabled}}"
            right: "production:true"
        - task_key: refresh_monitoring_dashboard
          description: Refresh the published shared dashboard after monitoring evidence is saved
          depends_on:
            - task_key: dashboard_refresh_enabled
              outcome: "true"
          timeout_seconds: ${{var.monitoring_task_timeout_seconds}}
          max_retries: ${{var.monitoring_max_retries}}
          min_retry_interval_millis: 60000
          dashboard_task:
              dashboard_id: {json.dumps(dashboard_id)}{warehouse}
"""
    path.write_text(
        HEADER
        + "targets:\n"
        + "".join(
            f"  {json.dumps(target)}:\n" + indent(resource, "    ")
            for target in dict.fromkeys(targets)
        ),
        encoding="utf-8",
    )
    return path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--dashboard-url", default="")
    source.add_argument("--dashboard-id", default="")
    source.add_argument("--disable", action="store_true")
    parser.add_argument("--warehouse-id", default="")
    parser.add_argument(
        "--target",
        action="append",
        help="Bundle target; repeat for multiple targets (default: test)",
    )
    args = parser.parse_args()
    overlay = configure(
        Path(__file__).resolve().parents[2],
        dashboard_id=args.dashboard_id,
        dashboard_url=args.dashboard_url,
        warehouse_id=args.warehouse_id,
        targets=tuple(args.target or ["test"]),
    )
    print("Dashboard refresh", "disabled" if args.disable else "configured", "in", overlay)
    print("Validate and redeploy the Bundle before running monitoring.")
