"""Generate a separate, optional feature job using existing deployment controls."""

import hashlib
import json
from copy import deepcopy
from dataclasses import asdict
from importlib.resources import files
from pathlib import Path
from typing import Any

from ..projects.yaml_config import read_yaml_mapping
from .config import FeaturePlan, parse_feature_config

_JOB_CONTROLS = (
    "tags",
    "run_as",
    "permissions",
    "environments",
    "job_clusters",
    "budget_policy_id",
    "timeout_seconds",
    "health",
    "email_notifications",
    "webhook_notifications",
)


def plan_digest(plan: FeaturePlan) -> str:
    """Identify the semantic feature graph and its ordered output schema."""
    return hashlib.sha256(json.dumps(asdict(plan), sort_keys=True).encode()).hexdigest()


def _task(name: str, phase: str, prototype: dict, parameters: dict) -> dict:
    """Reuse compute and time limits without inheriting lifecycle task state."""
    task = {
        key: deepcopy(prototype[key])
        for key in (
            "environment_key",
            "job_cluster_key",
            "existing_cluster_id",
            "libraries",
            "timeout_seconds",
            "disable_auto_optimization",
        )
        if key in prototype
    }
    task.update(task_key=name, max_retries=0, retry_on_timeout=False)
    task["notebook_task"] = {
        "notebook_path": "../src/jobs/feature_task.py",
        "base_parameters": {**parameters, "phase": phase},
    }
    return task


def build_feature_job(plan: FeaturePlan, training_job: dict[str, Any]) -> dict[str, Any]:
    """Create fan-out groups and fan-in merge with one pinned source snapshot."""
    job = {key: deepcopy(training_job[key]) for key in _JOB_CONTROLS if key in training_job}
    job.update(
        name="${bundle.name}_features",
        max_concurrent_runs=1,
        queue={"enabled": True},
        parameters=[{"name": "selected_groups", "default": "*"}],
    )
    prototype = next(task for task in training_job["tasks"] if "notebook_task" in task)
    params = {
        "config_path": "${workspace.file_path}/config/features.yml",
        "plan_sha256": plan_digest(plan),
        "selected_groups": "{{job.parameters.selected_groups}}",
    }
    tasks = [_task("initialize_features", "initialize", prototype, params)]
    params = {**params, "snapshot_json": "{{tasks.initialize_features.values.snapshot_json}}"}
    for group in plan.groups:
        task = _task(f"feature_{group.name}", "group", prototype, {**params, "group": group.name})
        task["depends_on"] = [{"task_key": "initialize_features"}]
        tasks.append(task)
    receipts = {
        f"receipt_{g.name}_json": f"{{{{tasks.feature_{g.name}.values.receipt_json}}}}"
        for g in plan.groups
    }
    merge = _task("merge_features", "merge", prototype, {**params, **receipts})
    merge["depends_on"] = [{"task_key": f"feature_{g.name}"} for g in plan.groups]
    tasks.append(merge)
    job["tasks"] = tasks
    return job


def _owned_target(root: Path, relative: str, marker: str) -> Path:
    """Resolve a generated file without following escaping project directories."""
    target = root / relative
    if not target.resolve().is_relative_to(root):
        raise ValueError("Feature resources must remain within the project directory.")
    if target.is_symlink() or (target.exists() and not target.read_text().startswith(marker)):
        raise ValueError("Refusing to replace a feature resource not owned by this generator.")
    return target


def _feature_targets(root: Path) -> dict[str, Any]:
    """Inherit target-specific training identities and permissions for this producer."""
    import yaml  # noqa: PLC0415

    path = root / "deployment/targets.yml"
    if not path.is_file():
        return {}
    targets = yaml.safe_load(path.read_text(encoding="utf-8")).get("targets", {})
    result = {}
    for name, target in targets.items():
        training = target.get("resources", {}).get("jobs", {}).get("train", {})
        controls = {key: deepcopy(training[key]) for key in _JOB_CONTROLS if key in training}
        if target.get("mode") == "development":
            controls["name"] = "features"
        if controls:
            result[name] = {"resources": {"jobs": {"features": controls}}}
    return result


def refresh_feature_graph(project: str | Path) -> list[str]:
    """Write the optional graph and notebook, preserving hand-owned project files."""
    import yaml  # noqa: PLC0415

    root = Path(project).resolve()
    plan = parse_feature_config(read_yaml_mapping(root / "config/features.yml"))
    marker = "# Generated by refresh_feature_graph.py; edit config/features.yml.\n"
    target = _owned_target(root, "resources/features.job.yml", marker)
    notebook = _owned_target(
        root, "src/jobs/feature_task.py", "# Databricks notebook source\n" + marker
    )
    if plan is None:
        target.unlink(missing_ok=True)
        notebook.unlink(missing_ok=True)
        return []
    training = yaml.safe_load((root / "resources/train.job.yml").read_text(encoding="utf-8"))
    job = build_feature_job(plan, training["resources"]["jobs"]["train"])
    source = (
        files("skyulf.integrations.databricks.jobs.features")
        .joinpath("notebook.py")
        .read_text(encoding="utf-8")
    )
    notebook.parent.mkdir(parents=True, exist_ok=True)
    notebook.write_text(source, encoding="utf-8")
    resource: dict[str, Any] = {"resources": {"jobs": {"features": job}}}
    targets = _feature_targets(root)
    if targets:
        resource["targets"] = targets
    target.write_text(
        marker + yaml.safe_dump(resource, sort_keys=False),
        encoding="utf-8",
    )
    return [group.name for group in plan.groups]
