"""Generate native CLI search-space catalogs from Core's parameter definitions.

Python is used only when maintaining this template. Bundle initialization reads
the committed Go helper and requires neither Python nor an installed Core SDK.
"""

import argparse
import importlib
import json
import sys
from pathlib import Path
from types import ModuleType
from typing import Any

ROOT = Path(__file__).resolve().parent


def _load_registry() -> ModuleType:
    """Import real parameter definitions without initializing optional ML libraries.

    The parameter package and shared types use only the standard library. Private
    namespace parents bypass the SDK's eager estimator imports without modifying
    or substituting any Core definitions. Remove that namespace after loading.
    """
    namespace = "_skyulf_bundle_catalog"
    core = ROOT.parents[1] / "skyulf"
    try:
        for suffix, path in (("", core), (".modeling", core / "modeling")):
            package = ModuleType(namespace + suffix)
            package.__path__ = [str(path)]
            sys.modules[package.__name__] = package
        return importlib.import_module(namespace + ".modeling.hyperparameters._registry")
    finally:
        for name in list(sys.modules):
            if name == namespace or name.startswith(namespace + "."):
                del sys.modules[name]


def _go_map(values: dict[str, Any]) -> str:
    """Encode deterministic native CLI maps whose leaves are JSON string literals."""
    pairs = []
    for key, value in sorted(values.items()):
        encoded = _go_map(value) if isinstance(value, dict) else json.dumps(value)
        pairs.append(f"(pair {json.dumps(key)} {encoded})")
    return "(map " + " ".join(pairs) + ")"


def _catalog(registry: ModuleType) -> dict[str, dict[str, dict[str, str]]]:
    """Serialize Core's compact and richer finite lists, rejecting invalid values."""
    catalog = {}
    for strategy in ("grid", "random"):
        models = {}
        for model in sorted(registry.DEFAULT_SEARCH_SPACES):
            if model.startswith(("voting_", "stacking_")):
                continue
            space = registry.get_default_search_space(model, strategy)
            models[model] = {
                key: json.dumps(values, allow_nan=False) for key, values in space.items()
            }
        catalog[strategy] = models
    return catalog


def render_model_spaces() -> str:
    """Render a JSON-object helper accepting model, task and initializer context.

    Context keys are ``model``, ``task``, ``strategy``, ``resource``, ``values``
    (all initializer inputs), and ``ensemble_prefix``. Only selected ensemble
    learners contribute axes; structural settings remain fixed in model params.
    """
    registry = _load_registry()
    mappings = {
        "classification": registry._BASE_KEY_TO_REGISTRY_CLF,
        "regression": registry._BASE_KEY_TO_REGISTRY_REG,
    }
    header = (
        "{{/* Generated by build_model_spaces.py; edit Core defaults and regenerate. */}}\n"
        '{{define "model_search_space" -}}\n'
        "{{$catalog := " + _go_map(_catalog(registry)) + " -}}\n"
        "{{$mappings := " + _go_map(mappings) + " -}}\n"
    )
    return header + _HELPER_BODY


_HELPER_BODY = r"""{{$family := "random" -}}
{{if or (eq .strategy "grid") (eq .strategy "halving_grid")}}{{$family = "grid"}}{{end -}}
{{$spaces := index $catalog $family -}}
{{$resource := "" -}}
{{if or (eq .strategy "halving_grid") (eq .strategy "halving_random")}}{{$resource = .resource}}{{end -}}
{{$first := true -}}
{{$indent := or (index . "indent") "" -}}
{
{{- if (regexp "^(voting|stacking)_").MatchString .model -}}
  {{$mapping := index $mappings .task -}}
  {{$values := .values -}}
  {{$prefix := .ensemble_prefix -}}
  {{$weightPrefix := "" -}}
  {{if (regexp "^branch_[1-8]_").MatchString $prefix -}}{{$weightPrefix = (regexp "^branch_[1-8]_").FindString $prefix -}}{{end -}}
  {{$suffix := "" -}}{{if eq (index $values (print $weightPrefix "sample_weight_enabled")) "true" -}}{{$suffix = "_weighted" -}}{{end -}}
  {{$count := index $values (printf "%s%s_base_count" $prefix .task) -}}
  {{$infix := "" -}}
  {{if and (eq .task "classification") (eq (index $values (printf "%scalibrate" $prefix)) "true")}}{{$infix = "estimator__"}}{{end -}}
  {{range $slot := (regexp "[0-9]+").FindAllString "1 2 3 4 5 6 7 8 9 10 11 12 13 14" -1 -}}
    {{if or (lt (len $slot) (len $count)) (and (eq (len $slot) (len $count)) (le $slot $count)) -}}
      {{$base := index $values (printf "%s%s_base_%s%s" $prefix $.task $slot $suffix) -}}
      {{range $param, $choices := index $spaces (index $mapping $base) -}}
        {{$key := printf "%s__%s%s" $base $infix $param -}}
        {{if ne $key $resource}}{{if not $first}},{{if not (index $ "python")}} {{end}}{{end}}{{if (index $ "python")}}{{printf "\n%s    " $indent}}{{end}}{{printf "%q" $key}}: {{if (index $ "python")}}{{template "python_value" $choices}}{{else}}{{$choices}}{{end}}{{$first = false}}{{end -}}
      {{end -}}
    {{end -}}
  {{end -}}
  {{if (regexp "^stacking_").MatchString .model -}}
    {{$final := index $values (printf "%s%s_final%s" $prefix .task $suffix) -}}
    {{range $param, $choices := index $spaces (index $mapping $final) -}}
      {{$key := printf "final_estimator__%s" $param -}}
      {{if ne $key $resource}}{{if not $first}},{{if not (index $ "python")}} {{end}}{{end}}{{if (index $ "python")}}{{printf "\n%s    " $indent}}{{end}}{{printf "%q" $key}}: {{if (index $ "python")}}{{template "python_value" $choices}}{{else}}{{$choices}}{{end}}{{$first = false}}{{end -}}
    {{end -}}
  {{end -}}
{{else -}}
  {{range $param, $choices := index $spaces .model -}}
    {{if ne $param $resource}}{{if not $first}},{{if not (index $ "python")}} {{end}}{{end}}{{if (index $ "python")}}{{printf "\n%s    " $indent}}{{end}}{{printf "%q" $param}}: {{if (index $ "python")}}{{template "python_value" $choices}}{{else}}{{$choices}}{{end}}{{$first = false}}{{end -}}
  {{end -}}
{{end -}}
{{- if and (index . "python") (not $first)}}{{printf "\n%s" $indent}}{{end}}}
{{- end}}
"""


def main() -> int:
    """Regenerate the committed helper or report stale output without writing."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the catalog is stale")
    options = parser.parse_args()
    output = ROOT / "library/model_search_space.tmpl"
    rendered = render_model_spaces()
    if options.check:
        if not output.exists() or output.read_text(encoding="utf-8") != rendered:
            print("Model spaces are out of date; run build_model_spaces.py.", file=sys.stderr)
            return 1
        print("Model spaces are up to date.")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Generated {output.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
